### PR TITLE
Feature/refactor changes

### PR DESCRIPTION
**Pull request by njhargis**
@swagbotbilly ignore the ! in the comments I did that so every file would be run against the formatter, as it only checks files that have changed.
This is what mine outputs.

### CODE REVIEW

**Comment by will-hedges** [comment]
This is the guide I followed: https://pre-commit.com/

So you're saying you think because I didn't have uncommitted changes, there wasn't anything for it to run against?

**Comment by njhargis** [comment]
No, it'll give you a specific message if it doesn't run against a file.
```
$ git commit -m "Testing hooks"
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
don't commit to branch...................................................Passed
print-msg............................................(no files to check)Skipped
- hook id: print-msg
On branch feature/refactor
Your branch is up to date with 'swagbot/feature/refactor'.
```

**Comment by njhargis** [comment]
I think the diff between our branches is only the line length
https://github.com/njhargis/creamy-cogs/compare/feature/refactor...feature/refactor-changes

**Comment by will-hedges** [comment]
Wait, does the hook perform the formatting or just check & prevent committing?

**Pull request closed without merging**
