### PR TITLE
minor refactoring

### PR DESCRIPTION
**Pull request by will-hedges**
* reordered imports per PEP8 (built-in modules > third-party modules > local imports)
* reordered regions in `leaguecog` `self.regions` in an estimate of likelihood of use, removed TODO
* removed old `logging` statements
* formatting with `black`

### CODE REVIEW

**Comment by njhargis** [comment]
Install the pre commit hooks so your formatting matches flake8 with 99 line length + black
99 because that’s what Red uses

**Comment by will-hedges** [comment]
Can you check if running the hooks from your side changes this branch? AFAIK I ran it correctly but nothing changed.

This is what I'm getting, and `git diff` shows no changes:
```
will@blue:~/Code/GitHub/creamy-cogs$ pre-commit run --all-files
black....................................................................Passed
flake8...................................................................Passed
don't commit to branch...................................................Passed
print-msg................................................................Passed
- hook id: print-msg
- duration: 0s

uses black styling, flake8 linting, and branch name must begin with bugfix/ or feature/
 .github/ISSUE_TEMPLATE/bug_report.md creamycog/info.json .pre-commit-config.yaml leaguecog/ezreal.py leaguecog/blitzcrank.py
uses black styling, flake8 linting, and branch name must begin with bugfix/ or feature/
 .flake8 leaguecog/info.json pyproject.toml .github/ISSUE_TEMPLATE/feature_request.md creamycog/creamycog.py
uses black styling, flake8 linting, and branch name must begin with bugfix/ or feature/
 .gitignore creamycog/__init__.py leaguecog/__init__.py leaguecog/leaguecog.py .vscode/settings.json
uses black styling, flake8 linting, and branch name must begin with bugfix/ or feature/
 README.md leaguecog/mixinmeta.py
 ```

**Comment by njhargis** [comment]
```
$ git commit -m "Testing hooks"
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted leaguecog\blitzcrank.py
reformatted leaguecog\leaguecog.py

All done! \u2728 \U0001f370 \u2728
2 files reformatted, 1 file left unchanged.

flake8...................................................................Failed
- hook id: flake8
- exit code: 1

leaguecog/leaguecog.py:173:9: F841 local variable 'ser' is assigned to but never used

don't commit to branch...................................................Passed
print-msg................................................................Passed
- hook id: print-msg
- duration: 0.04s

uses black styling, flake8 linting, and branch name must begin with bugfix/ or feature/
 leaguecog/blitzcrank.py leaguecog/ezreal.py leaguecog/leaguecog.py

```

**Comment by will-hedges** [comment]
Weird. I wonder what I've done wrong

**Comment by will-hedges** [comment]
Ok should be set up now. I saw where the commit checks ran this time.

I had to change the `.yaml` to python3.9 to push changes, so let me know if we just need to add it to `.gitignore` for now or if you're going to update to 3.9

**Review by njhargis — APPROVED** [review]

**Pull request merged**
